[package]
name = "textexcel_lib"
version = "0.0.6"
authors = ["tzip"]
edition = "2018"

[workspace]
members =[
    "textexcel_gui",
    "cli"
]
[dependencies]
textexcelport_core = {version = "0.1.0", path = "core" }
