[package]
name = "TextExcelPort"
version = "0.0.6"
authors = ["tzip"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90", features = ["derive","rc"] }
serde_json = "1.0"
lazy_static = "1.4.0"
